FROM ubuntu:latest AS bot
RUN apt-get update && apt-get install -y supervisor

# Set the working directory to /app
WORKDIR /app

COPY ./wechat/wechat  /app/wechat
COPY ./telegram/telegram  /app/telegram
COPY ./role/role.yaml  /app/wechat
COPY ./role/role.yaml  /app/telegram

# 启动 supervisor 进程管理器
CMD ["/usr/bin/supervisord", "-n"]
