 

# Use an official Ubuntu image as a parent image
FROM ubuntu:latest AS server

# Set the working directory to /app
WORKDIR /app
RUN mkdir /app/logs
RUN mkdir /app/file
RUN mkdir /app/db

# Copy the current directory contents into the container at /app
COPY ./server/server  /app
COPY ./role/role.yaml  /app

# Expose port 8080 to the outside world
EXPOSE 8080

CMD ["./server"]