version: '3'
services:
  gateway:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /path/to/ca/file:/etc/nginx/ssl
      - ./gateway.conf:/etc/nginx/conf.d/default.conf
      - /data/logs:/var/log/nginx
    networks:
      - appnet
  api:
    image: guojingneo/chat-server:v1.1.0-c9154cc-amd64-amd64
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - app.env
    volumes:
      - ./config.yaml:/app/config.yaml
      - /data/logs:/app/logs
      - /data/db:/app/db
      - /data/file:/app/file
    networks:
      - appnet
  wechat:
    image: guojingneo/wechat:v1.1.0-c9154cc-amd64-amd64
    restart: always
    env_file:
      - ./app.env
    volumes:
      - ./wechat.yaml:/app/config.yaml
      - ./config.json:/app/config.json
      - ./supervisord_wechat.conf:/etc/supervisor/conf.d/supervisord.conf
      - /data/logs:/app/logs
      - /data/db:/app/db
      - /data/file:/app/file
    networks:
      - appnet
  telegram:
    image: guojingneo/tg:v1.1.0-c9154cc-amd64-amd64
    restart: always
    env_file:
      - ./app.env
    volumes:
      - ./telegram.yaml:/app/config.yaml
      - ./supervisord_tg.conf:/etc/supervisor/conf.d/supervisord.conf
      - /data/logs:/app/logs
      - /data/db:/app/db
      - /data/file:/app/file
    networks:
      - appnet
  mytelegram:
    image: guojingneo/telegram:v1.0.0
    restart: always
    env_file:
      - ./app.env
    volumes:
      - ./mofeise.session:/app/mofeise.session
      - /data/db:/app/db
      - /data/file:/app/file
    networks:
      - appnet
networks:
  appnet:
    driver: bridge

