version: '3'
services:
  gateway:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf
      - logs:/var/log/nginx
    networks:
      - appnet
  api:
    image: your-app1-image
    environment:
      LOG_PATH: ${LOG_PATH}
      DB_PATH: ${DB_PATH}
      FILE_PATH: ${FILE_PATH}
    volumes:
      - ./config.yaml:/app/config.yaml
      - logs:${LOG_PATH}
      - db:${DB_PATH}
      - file:${FILE_PATH}
    networks:
      - appnet
  bot:
    image: your-app1-image
    environment:
      LOG_PATH: ${LOG_PATH}
      DB_PATH: ${DB_PATH}
      FILE_PATH: ${FILE_PATH}
    volumes:
      - ./telegram.yaml:/app/telegram/config.yaml
      - ./wechat.yaml:/app/wechat/config.yaml
      - ./config.json:/app/config.json
      - ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf
      - logs:${LOG_PATH}
      - db:${DB_PATH}
      - file:${FILE_PATH}
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
volumes:
  file:
    driver_opts:
      type: none
      device: /data/file
  logs:
    driver_opts:
      type: none
      device: /data/logs
  db:
    driver_opts:
      type: none
      device: /data/db

