version: '3'
services:
  gateway:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf
      - logs:/var/log/nginx
    networks:
      - appnet
  api:
    image: your-app1-image
    env_file:
      - ./app.env
    volumes:
      - ./config.yaml:/app/config.yaml
      - logs:${LOG_PATH}
      - db:${DB_PATH}
      - file:${FILE_PATH}
    networks:
      - appnet
  wechat:
    image: your-app1-image
    env_file:
      - ./app.env
    volumes:
      - ./wechat.yaml:/app/config.yaml
      - ./config.json:/app/config.json
      - ./supervisord_wechat.conf:/etc/supervisor/conf.d/supervisord.conf
      - logs:${LOG_PATH}
      - db:${DB_PATH}
      - file:${FILE_PATH}
    networks:
      - appnet
  telegram:
    image: your-app1-image
    env_file:
      - ./app.env
    volumes:
      - ./telegram.yaml:/app/config.yaml
      - ./supervisord_tg.conf:/etc/supervisor/conf.d/supervisord.conf
      - logs:${LOG_PATH}
      - db:${DB_PATH}
      - file:${FILE_PATH}
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
volumes:
  file:
    driver_opts:
      type: none
      device: /data/file
  logs:
    driver_opts:
      type: none
      device: /data/logs
  db:
    driver_opts:
      type: none
      device: /data/db

