version: '3'
services:
  gateway:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./gateway.conf:/etc/nginx/conf.d/default.conf
    networks:
      - appnet
  api:
    image: your-app1-image
    volumes:
      - ./config.yaml:/app/config.yaml
    networks:
      - appnet
  bot:
    image: your-app1-image
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./config.json:/app/config.json
      - ./supervisord.conf /etc/supervisor/conf.d/supervisord.conf
    networks:
      - appnet
networks:
  appnet:
    driver: bridge